package org.zgl.jetty.builder_clazz;
public class CommandCode{
	public static final int LoginHandler = 1;
	public static final int LoginHandler_2 = 2;
	public static final int GiftBagCmd = 3;
	public static final int FriendRequestList = 4;
	public static final int FriendSendGift = 5;
	public static final int FriendHandler = 6;
	public static final int ShopBuy_vip = 7;
	public static final int MoneyTree = 8;
	public static final int OnlineAwardCmd = 9;
	public static final int AcitivityCmd = 10;
	public static final int RankingCmd = 11;
	public static final int FirstBuyCmd = 12;
	public static final int DialCmd = 13;
	public static final int RequestTaskList = 14;
	public static final int RequestTaskGetAward = 15;
	public static final int SignIn = 16;
	public static final int Logout = 17;
	public static final int IntoRoom = 18;
	public static final int AutoUse = 19;
	public static final int PlayerWeath = 20;
	public static final int RequestPlayerInfo = 21;
	public static final int ShopBuy_auto = 22;
	public static final int ShopBuy_exchange = 23;
	public static final int ShopBuy_gold = 24;
	public static final int ShopBuy_moneyTree = 25;
	public static final int ShopBuy_prop = 26;
	public static final int RoomPlayerInfo = 10000;
	public static final int RoomUpdateWeath = 10001;
	public static final int IntoHall = 10002;
	public static final int RoomPlayerErrorLogout = 10003;
	public static final int FirstRoomChange = 10006;
}
